
services:
  postgres:
    network_mode: "host"
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready --username=postgres
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    network_mode: "host"  
    build:
      context: .  
    command: poetry run unrest db reset
    volumes:
      - ".:/host"
    depends_on:
      postgres:
        condition: service_healthy 


  # redis:
  #   network_mode: "host"
  #   image: redis

  # scheduler:
  #   network_mode: "host"  
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ".:/host"
  #   command: poetry run taskiq scheduler entrypoint:scheduler
  #   depends_on: 
  #     redis:
  #       condition: service_started

  # broker:
  #   network_mode: "host"  
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ".:/host"
  #   command: poetry run taskiq worker entrypoint:broker --reload
  #   depends_on: 
  #     redis:
  #       condition: service_started
  #     migration:
  #       condition: service_completed_successfully        

  api:
    network_mode: "host"  
    build:
      context: .
    volumes:
      - ".:/host"
    command: poetry run uvicorn entrypoint:server --host "0.0.0.0" --port 8080
    depends_on:
      postgres:
        condition: service_healthy     
      migration:
        condition: service_completed_successfully
